// <auto-generated />
namespace ReviewWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedtostoringauthoruseridandsubjectuserid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedtostoringauthoruseridandsubjectuserid));
        
        string IMigrationMetadata.Id
        {
            get { return "201905151348497_changed to storing authoruserid and subjectuserid"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
